### ISSUE TITLE
Error in library(janeaustenr): there is no package called ‘janeaustenr’

### ISSUE THREAD

**Issue by GeorgeMcGinn** [juliasilge/janeaustenr#11]
When running the first test code in the book "Text Mining With R" I get `Error in library(janeaustenr): there is no package called ‘janeaustenr’`

I followed the install instructions outlined in the book from the URL `https://cran.r-project.org/package=janeaustenr`

I also verified that the library was loaded successfully.  I get the following in my listing of installed packages:
`janeaustenr 1.0.0.9000` 

I also verified (using `??janeaustenr` in my R terminal)  and got:
```
janeaustenr::austen_books
                        Tidy data frame of Jane Austen's 6 completed,
                        published novels
janeaustenr::emma       The text of Jane Austen's novel "Emma"
janeaustenr::janeaustenr
                        janeaustenr: Jane Austen's Complete Novels
  Aliases: janeaustenr, janeaustenr-package
janeaustenr::mansfieldpark
                        The text of Jane Austen's novel "Mansfield
                        Park"
janeaustenr::northangerabbey
                        The text of Jane Austen's novel "Northanger
                        Abbey"
janeaustenr::persuasion
                        The text of Jane Austen's novel "Persuasion"
janeaustenr::prideprejudice
                        The text of Jane Austen's novel "Pride and
                        Prejudice"
janeaustenr::sensesensibility
                        The text of Jane Austen's novel "Sense and
                        Sensibility"
```

Here is the source code I am running. My current version of R is: 4.1.0 on Ubuntu 20.04.

```
library(janeaustenr)
library(dplyr)
library(stringr)

original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text,
                                     regex("^chapter [\\divxlc]",
                                           ignore_case = TRUE)))) %>%
  ungroup()

original_books
```

**Comment by juliasilge** [comment]
To install this package, you will need to do `install.packages("janeaustenr")`. If you are having trouble with loading the package even though you have installed it, I recommend restarting R, doing `install.packages("janeaustenr")`, then restarting R again. You may have a bit of a borked session getting in the way.

**Comment by GeorgeMcGinn** [comment]
I did all that, and did not work. I even shut my machine down and rebooted. All my other packages still work, including shiny. So I tried it on my Windows machine and it works. The only thing I can think of is that it doesn't work in R v4.1.0. My Windows install has R v4.2.2 (10/31/2022 build). Ubuntu's repository does not have the latest version of R (v4.2). I'll try and install that sometime this week (I hope it doesn't bork up my VSCode, which I use for development of other projects). If that sounds right (does not work in v4.1 of R) then you can close this out. If it should, I will look into this deeper. Thanks.

**Comment by juliasilge** [comment]
No, it definitely should work in R 4.1. Can you create a [reprex](https://reprex.tidyverse.org/) (a minimal reproducible example) for this? The goal of a reprex is to make it easier for us to recreate your problem so that we can understand it and/or fix it. If you've never heard of a reprex before, you may want to start with the [tidyverse.org help](https://www.tidyverse.org/help/) page. You could try one like this:

``` r
head(janeaustenr::emma, 20)
#>  [1] "EMMA"                                                                   
#>  [2] ""                                                                       
#>  [3] "By Jane Austen"                                                         
#>  [4] ""                                                                       
#>  [5] ""                                                                       
#>  [6] ""                                                                       
#>  [7] ""                                                                       
#>  [8] "VOLUME I"                                                               
#>  [9] ""                                                                       
#> [10] ""                                                                       
#> [11] ""                                                                       
#> [12] "CHAPTER I"                                                              
#> [13] ""                                                                       
#> [14] ""                                                                       
#> [15] "Emma Woodhouse, handsome, clever, and rich, with a comfortable home"    
#> [16] "and happy disposition, seemed to unite some of the best blessings of"   
#> [17] "existence; and had lived nearly twenty-one years in the world with very"
#> [18] "little to distress or vex her."                                         
#> [19] ""                                                                       
#> [20] "She was the youngest of the two daughters of a most affectionate,"
```

<sup>Created on 2022-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

It may be helpful to use `session_info = TRUE` in this case since I suspect the problem is something outside of janeaustenr. Thanks! 🙌

**Comment by GeorgeMcGinn** [comment]
I ran it, and look at it - it works. I copied the code to my clipboard, generated the reprex, and I got the expected output (below).

That got me thinking. Maybe it is a VSCode issue. So I ran my code again directly into the R terminal session, and it ran fine. I'll let you know what I find out as far as why VSCode may be borking my run on this. However, if you have any ideas, or have heard about this before, please let me know, 

Thanks.

``` r
library(janeaustenr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(stringr)
library(tidytext)

original_books <- austen_books() %>%
  group_by(book) %>%
  mutate(linenumber = row_number(),
         chapter = cumsum(str_detect(text,
                                     regex("^chapter [\\divxlc]",
                                           ignore_case = TRUE)))) %>%
  ungroup()

original_books
#> # A tibble: 73,422 × 4
#>    text                    book                linenumber chapter
#>    <chr>                   <fct>                    <int>   <int>
#>  1 "SENSE AND SENSIBILITY" Sense & Sensibility          1       0
#>  2 ""                      Sense & Sensibility          2       0
#>  3 "by Jane Austen"        Sense & Sensibility          3       0
#>  4 ""                      Sense & Sensibility          4       0
#>  5 "(1811)"                Sense & Sensibility          5       0
#>  6 ""                      Sense & Sensibility          6       0
#>  7 ""                      Sense & Sensibility          7       0
#>  8 ""                      Sense & Sensibility          8       0
#>  9 ""                      Sense & Sensibility          9       0
#> 10 "CHAPTER 1"             Sense & Sensibility         10       1
#> # … with 73,412 more rows

tidy_books <- original_books %>%
  unnest_tokens(word, text)

tidy_books
#> # A tibble: 725,055 × 4
#>    book                linenumber chapter word       
#>    <fct>                    <int>   <int> <chr>      
#>  1 Sense & Sensibility          1       0 sense      
#>  2 Sense & Sensibility          1       0 and        
#>  3 Sense & Sensibility          1       0 sensibility
#>  4 Sense & Sensibility          3       0 by         
#>  5 Sense & Sensibility          3       0 jane       
#>  6 Sense & Sensibility          3       0 austen     
#>  7 Sense & Sensibility          5       0 1811       
#>  8 Sense & Sensibility         10       1 chapter    
#>  9 Sense & Sensibility         10       1 1          
#> 10 Sense & Sensibility         13       1 the        
#> # … with 725,045 more rows
```

<sup>Created on 2022-11-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by GeorgeMcGinn** [comment]
I figured it out. When I installed the package, I must have run R in sudo. When I execute this particular code, it must write something to the directory that it was installed on. This is why this script will not run in either VSCode or Geany IDE's. I tested this by starting Geany in sudo, and the R code ran. I am closing this out, and will fix this. (Another Forest Gump moment for me!)

**Comment by juliasilge** [comment]
Glad you figured it out!
