### ISSUE TITLE
DESCRIPTION lies about the version

### ISSUE THREAD

**Issue by barracuda156** [juliasilge/janeaustenr#12]
1.0.0 still has 0.1.5 in DESCRIPTION.

**Comment by juliasilge** [comment]
Can you say more about where you are seeing this? The current DESCRIPTION file on GitHub has this:

https://github.com/juliasilge/janeaustenr/blob/2b8d5936ca112bb0b3dfc9ebd97c64c345c09fcf/DESCRIPTION#L3

**Comment by barracuda156** [comment]
@juliasilge As I mention above, it is in v1.0.0 (not the master): https://github.com/juliasilge/janeaustenr/blob/944e9a5ff62e40175dcf5bcacd7bda0a3ec673b6/DESCRIPTION#L3

**Comment by juliasilge** [comment]
Hmmmm, not quite sure what you are saying here. You can see the commits here:
https://github.com/juliasilge/janeaustenr/commits/main

Notice that commit 944e9a5ff62e40175dcf5bcacd7bda0a3ec673b6 is before v1.0.0 went to CRAN. Can you say a bit more about the problem you are observing?

**Comment by barracuda156** [comment]
@juliasilge The tarball has the wrong version. The one here: https://github.com/juliasilge/janeaustenr/releases/tag/v1.0.0

**Comment by juliasilge** [comment]
Ah gotcha! I must have made an error in doing the GitHub release. Apologies about that! I recommend that you install from CRAN or R-universe rather than a GitHub release:

- https://cran.r-project.org/package=janeaustenr
- https://juliasilge.r-universe.dev/janeaustenr

**Comment by barracuda156** [comment]
Yeah, I am aware of those options, I just pointed out the issue with a tarball here.
I am adding `janeaustenr` to Macports, will use commit-based portfile for now (i.e. build from the master branch).
(`r-universe` does stealth updates which break checksums, and I tend to prefer upstream over CRAN.)

**Comment by barracuda156** [comment]
FYI, added: https://ports.macports.org/port/R-janeaustenr
