### ISSUE TITLE
Character encoding is "unknown" but should be "latin1"

### ISSUE THREAD

**Issue by patperry** [juliasilge/janeaustenr#4]
Thanks for your work on this package, it's a great resource for people looking for text data analysis examples. Unfortunately, there's a small problem with the encoding for *Mansfield Park*:

```
> Encoding(mansfieldpark[15222])
[1] "UTF-8"

> mansfieldpark[15222]
[1] "the command of her beauty, and her \xa320,000, any one who could satisfy the"
```

The `\xa3` is probably meant to encode a pound sign, [U+00A3](http://www.fileformat.info/info/unicode/char/00A3/index.htm). Note, however, that the UTF-8 encoding of U+00A3 is `\xc2\xa3`. I think the text is probably encoded in Latin-1, where the encoding of U+00A3 is `\xa3`. 

If we set the encoding to "latin1", then we display the correct symbol:
```
> Encoding(mansfieldpark) <- "latin1"

> mansfieldpark[15222]
[1] "the command of her beauty, and her £20,000, any one who could satisfy the"
```
This leads me to believe that the texts are encoded in Latin-1 but declared to be UTF-8. This will cause problems for other packages, including [corpus](https://github.com/patperry/r-corpus), which refuses to process invalid UTF-8.

There are two easy fixes:

1. Set the encoding to Latin-1:

```
Encoding(mansfieldpark) <- "latin1"
```

2. Alternatively, convert the Latin-1 data to UTF-8:

```
mansfieldpark <- iconv(mansfieldpark, "latin1", "UTF-8")
```

If you want to make sure that the conversion worked, you can try `corpus::as_text(mansfieldpark)`, which will fail if the data is invalid. It looks like the other books are all valid UTF-8.

**Comment by juliasilge** [comment]
Thanks so much for bringing this to my attention! 🙌
